### ISSUE TITLE
truedark-vim.vim should be under a colors subdirectory

### ISSUE THREAD

**Issue by rickprice** [bratpeki/truedark-vim#1]
So, in your Git repository you should create a colors subdirectory and move truedark-vim into it.

Otherwise Vim-Plug doesn't work with it, and you can't find the colorscheme even though the plugin loads...

**Comment by bratpeki** [comment]
> So, in your Git repository you should create a colors subdirectory and move truedark-vim into it.
> 
> Otherwise Vim-Plug doesn't work with it, and you can't find the colorscheme even though the plugin loads...

@rickprice Are you aware of any ways to solve this other than manually creating a `colors` folder? If not, I'll just update the README with valid information.

**Comment by rickprice** [comment]
I will try to send you a PR tomorrow, what I am suggesting is straightforward, but maybe you won't like it...

Rick
